In [21]:
import numpy as np

In [22]:
from nestmodel.fast_graph import FastGraph

In [23]:
from networkx.readwrite import from_graph6_bytes
from tqdm.notebook import tqdm

In [26]:
from nestmodel.io import g6_read_bytes, g6_bytes_to_edges

In [28]:
%%time
g6_bytes = g6_read_bytes(r"L:/tmp/Isomorphism/graph10c.g6")

CPU times: total: 2.34 s
Wall time: 2.33 s


In [30]:
%%time
g6_edges = g6_bytes_to_edges(g6_bytes)

11716571
CPU times: total: 19.3 s
Wall time: 19.4 s


In [37]:
from collections import defaultdict, Counter
def calc_sequence(colors):
    for c1, c2 in zip(colors, colors[1:]):
        d = defaultdict(Counter)
        for i, j in zip(c2, c1):
            d[i][j]+=1
        print(d)
        

In [39]:
from nestmodel.fast_wl import WL_fast
from nestmodel.utils import make_directed

In [40]:
from collections import defaultdict

In [41]:
from tqdm.notebook import tqdm

In [44]:
graphs_by_iteration_number = defaultdict(list)
for edges in tqdm(g6_edges):
    edges = make_directed(edges)
    num_iterations = len(WL_fast(edges, method="nlogn", compact=False))
    if num_iterations>=8:
        graphs_by_iteration_number[num_iterations].append(edges)

  0%|          | 0/11716571 [00:00<?, ?it/s]

In [59]:
len(graphs_by_iteration_number[10])

16

In [60]:
len(graphs_by_iteration_number[11])

0

In [61]:
s=""
for edges in graphs_by_iteration_number[10]:
    s += repr(edges)+"\n"

In [62]:
print(s.replace(",\n", ","))

array([[0, 4],       [1, 5],       [2, 5],       [0, 6],       [3, 6],       [4, 6],       [0, 7],       [1, 7],       [3, 7],       [1, 8],       [2, 8],       [4, 8],       [0, 9],       [2, 9],       [3, 9],       [5, 9],       [4, 0],       [5, 1],       [5, 2],       [6, 0],       [6, 3],       [6, 4],       [7, 0],       [7, 1],       [7, 3],       [8, 1],       [8, 2],       [8, 4],       [9, 0],       [9, 2],       [9, 3],       [9, 5]], dtype=int16)
array([[0, 4],       [1, 5],       [2, 5],       [0, 6],       [1, 6],       [3, 6],       [0, 7],       [2, 7],       [4, 7],       [0, 8],       [1, 8],       [2, 8],       [3, 8],       [1, 9],       [2, 9],       [6, 9],       [7, 9],       [4, 0],       [5, 1],       [5, 2],       [6, 0],       [6, 1],       [6, 3],       [7, 0],       [7, 2],       [7, 4],       [8, 0],       [8, 1],       [8, 2],       [8, 3],       [9, 1],       [9, 2],       [9, 6],       [9, 7]], dtype=int16)
array([[0, 4],       [1, 5],       [2, 5],    

In [ ]:
def get_moves(colorings):
    s = ""
    
    for colors, next_colors  in zip(colorings, colorings[1:]):
        count_prev = defaultdict(int)
        count_now = defaultdict(int)
        mapping = {c:prev_c for prev_c, c in zip(colors, next_colors) }
        for prev_c, c in zip(colors, next_colors):
            count_prev[prev_c]+=1
            count_now[c]+=1
        for c, prev_c in mapping.items():
            if count_now[c] == count_prev[prev_c]:
                continue
            if count_prev[prev_c] != 2 and count_now[c] == 1:
                s+="E"
                break
            elif count_prev[prev_c] == 2 and count_now[c] == 1:
                s+="A"
                break
            else:
                s+="R"
                break
    return s

In [ ]:
get_moves(WL_fast(G.edges, method="nlogn"))

In [ ]:
get_moves(WL_fast(G2.edges, method="nlogn"))

In [ ]:
G.calc_wl()

In [ ]:
calc_sequence(G.calc_wl())