In [1]:
import numpy as np

In [2]:
from nestmodel.fast_graph import FastGraph
from nestmodel.long_refinement_graphs import long_refinement_12__1_5, long_refinement_14__1_3, long_refinement_10
from nestmodel.utils import make_directed

In [3]:
G1 = long_refinement_14__1_3()
G2 = long_refinement_12__1_5()

In [4]:
from nestmodel.fast_wl import WL_fast

In [5]:
WL_fast(make_directed(G1.edges), method="nlogn")

[array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([0, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([0, 2, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([0, 2, 3, 3, 1, 1, 1, 1, 1, 1, 4, 4, 4, 4]),
 array([0, 2, 3, 3, 1, 1, 1, 1, 1, 1, 4, 4, 5, 5]),
 array([0, 2, 3, 3, 1, 1, 1, 1, 6, 6, 4, 4, 5, 5]),
 array([0, 2, 3, 3, 1, 1, 7, 7, 6, 6, 4, 4, 5, 5]),
 array([0, 2, 3, 3, 1, 1, 7, 7, 6, 6, 4, 8, 5, 5]),
 array([0, 2, 9, 3, 1, 1, 7, 7, 6, 6, 4, 8, 5, 5]),
 array([ 0,  2,  9,  3,  1,  1,  7,  7,  6,  6,  4,  8,  5, 10]),
 array([ 0,  2,  9,  3,  1,  1,  7,  7, 11,  6,  4,  8,  5, 10]),
 array([ 0,  2,  9,  3,  1,  1,  7, 12, 11,  6,  4,  8,  5, 10]),
 array([ 0,  2,  9,  3, 13,  1,  7, 12, 11,  6,  4,  8,  5, 10])]

In [36]:
from collections import defaultdict
def get_moves(colorings):
    """Calculates the a move string corresponding to a long refinement graph
    The three letters are
    E : a single node is removed from a larger color
    R : a color with more than 4 nodes is split into two colors where none of the colors has size 1
    A : a color with two nodes is split into two singleton nodes
    """
    s = ""
    
    for colors, next_colors  in zip(colorings, colorings[1:]):
        count_prev = defaultdict(int)
        count_now = defaultdict(int)
        mapping = {c:prev_c for prev_c, c in zip(colors, next_colors) }
        for prev_c, c in zip(colors, next_colors):
            count_prev[prev_c]+=1
            count_now[c]+=1
        found = False
        for c, prev_c in mapping.items():
            if count_now[c] == count_prev[prev_c]:
                continue
            if count_prev[prev_c] != 2 and count_now[c] == 1:
                found=True
                s+="E"
                break
            elif count_prev[prev_c] == 2 and count_now[c] == 1:
                found=True
                s+="A"
                break
            else:
                continue
        if not found:
            s+="R"
    return s

In [37]:
get_moves(WL_fast(make_directed(G1.edges), method="nlogn", compact=False))

'EERRRRRAAAAAA'

In [38]:
get_moves(WL_fast(make_directed(G2.edges), method="nlogn", compact=False))

'EERRRRAAAAA'

In [43]:
for i in range(16):
    edges = long_refinement_10(i, return_graph=False)
    print(get_moves(WL_fast(make_directed(edges), method="nlogn", compact=False)))
    print(np.bincount(edges.ravel())//2)

RRRRAAAAA
[4 3 3 3 3 3 3 3 3 4]
RERERAAAA
[4 4 4 2 2 2 4 4 4 4]
RRRRAAAAA
[4 4 3 3 4 4 3 3 4 4]
RRRRAAAAA
[4 3 4 3 4 3 4 3 4 4]
RRRRAAAAA
[4 4 4 4 4 4 4 4 5 5]
RRRRAAAAA
[4 4 4 4 4 4 4 4 6 6]
RRRRAAAAA
[5 5 3 3 5 3 3 5 5 5]
RRRRAAAAA
[4 4 4 4 4 4 5 5 5 5]
RRRRAAAAA
[4 4 4 4 4 4 6 6 6 6]
RRRRAAAAA
[4 4 5 5 5 4 5 4 5 5]
RRRRAAAAA
[5 5 3 5 3 5 5 5 5 5]
RRRRAAAAA
[5 5 4 5 5 5 5 4 5 5]
RRRRAAAAA
[5 5 5 5 6 6 5 5 6 6]
RRRRAAAAA
[5 5 5 5 5 5 6 6 6 6]
RERERAAAA
[5 5 5 5 5 5 5 7 7 7]
RRRRAAAAA
[5 6 6 6 6 5 6 6 6 6]


In [40]:
from collections import Counter
i=1
edges = long_refinement_10(i, return_graph=False)
s = get_moves(WL_fast(make_directed(edges), method="nlogn", compact=False))
print(s)
print(Counter(s))
WL_fast(make_directed(edges), method="nlogn", compact=False)

RERERAAAA
Counter({'A': 4, 'R': 3, 'E': 2})


[array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([3, 3, 3, 0, 0, 0, 3, 3, 3, 3]),
 array([3, 3, 3, 0, 0, 0, 3, 3, 3, 9]),
 array([3, 4, 4, 0, 0, 0, 4, 4, 3, 9]),
 array([3, 4, 4, 1, 1, 0, 4, 4, 3, 9]),
 array([3, 5, 5, 1, 1, 0, 4, 4, 3, 9]),
 array([3, 5, 5, 1, 1, 0, 4, 4, 8, 9]),
 array([3, 5, 5, 2, 1, 0, 4, 4, 8, 9]),
 array([3, 5, 5, 2, 1, 0, 7, 4, 8, 9]),
 array([3, 6, 5, 2, 1, 0, 7, 4, 8, 9])]