In [7]:
import networkx as nx
import numpy as np

In [23]:
G = nx.Graph()
G.add_nodes_from(range(7))
G.add_edges_from([(0,3), (0,4), (1,3), (1,6), (2,4), (2,5), (3,6), (4,5), (5,6)])

In [24]:
A = nx.adjacency_matrix(G).todense()
A

array([[0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 1, 1, 0],
       [1, 1, 0, 0, 0, 0, 1],
       [1, 0, 1, 0, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0]], dtype=int32)

In [25]:
H4 = np.zeros((7,4), dtype=int)
H4[0,0]=1
H4[1:3,1]=1
H4[3:5,2]=1
H4[5:7,3]=1
H4

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1]])

In [26]:
A@H4

array([[0, 0, 2, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 1],
       [1, 1, 0, 1],
       [1, 1, 0, 1],
       [0, 1, 1, 1],
       [0, 1, 1, 1]])

In [32]:
Api = np.array(
    [[0,0,2,0],
     [0,0,1,1],
     [1,0,1,1],
     [0,1,1,1]]
    ,dtype=int)

In [33]:
H4@Api

array([[0, 0, 2, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 1],
       [1, 0, 1, 1],
       [1, 0, 1, 1],
       [0, 1, 1, 1],
       [0, 1, 1, 1]])

In [35]:
H4.T@A@H4

array([[0, 0, 2, 0],
       [0, 0, 2, 2],
       [2, 2, 0, 2],
       [0, 2, 2, 2]])

In [43]:
Api@np.diag(1/np.sum(H4.T@A@H4,axis=1))@H4.T@A@H4

array([[0.66666667, 0.66666667, 0.        , 0.66666667],
       [0.33333333, 0.66666667, 0.33333333, 0.66666667],
       [0.33333333, 0.66666667, 1.33333333, 0.66666667],
       [0.33333333, 0.66666667, 0.83333333, 1.16666667]])

In [44]:
np.diag(1/np.sum(H4.T@A@H4,axis=1))@H4.T@A@H4

array([[0.        , 0.        , 1.        , 0.        ],
       [0.        , 0.        , 0.5       , 0.5       ],
       [0.33333333, 0.33333333, 0.        , 0.33333333],
       [0.        , 0.33333333, 0.33333333, 0.33333333]])

In [48]:
Api @ np.diag(1/np.sum(H4.T@A@H4,axis=1))@H4.T@A@H4

array([[0.66666667, 0.66666667, 0.        , 0.66666667],
       [0.33333333, 0.66666667, 0.33333333, 0.66666667],
       [0.33333333, 0.66666667, 1.33333333, 0.66666667],
       [0.33333333, 0.66666667, 0.83333333, 1.16666667]])

In [49]:
(Api.T @ np.diag(1/np.sum(H4.T@A@H4,axis=1))@H4.T@A@H4).sum(axis=1)

array([1., 1., 5., 3.])

In [50]:
(Api @ np.diag(1/np.sum(H4.T@A@H4,axis=1))@H4.T@A@H4).sum(axis=1)

array([2., 2., 3., 3.])

In [51]:
Api @ np.diag(1/np.sum(H4.T@A@H4,axis=1))@H4.T@A@H4

array([[0.66666667, 0.66666667, 0.        , 0.66666667],
       [0.33333333, 0.66666667, 0.33333333, 0.66666667],
       [0.33333333, 0.66666667, 1.33333333, 0.66666667],
       [0.33333333, 0.66666667, 0.83333333, 1.16666667]])

In [53]:
np.diag(1/np.sum(H4.T@A@H4,axis=1))@H4.T@A@H4

array([[0.        , 0.        , 1.        , 0.        ],
       [0.        , 0.        , 0.5       , 0.5       ],
       [0.33333333, 0.33333333, 0.        , 0.33333333],
       [0.        , 0.33333333, 0.33333333, 0.33333333]])

In [56]:
Api.T@np.diag(1/np.sum(H4.T@A@H4,axis=1))@H4.T@A@H4


array([[0.33333333, 0.33333333, 0.        , 0.33333333],
       [0.        , 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.66666667, 2.83333333, 1.16666667],
       [0.33333333, 0.66666667, 0.83333333, 1.16666667]])

In [64]:
Api.T@np.diag(1/np.sum(H4.T@A@H4,axis=1))@Api.T@H4.T@H4

array([[0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.        , 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.66666667, 2.66666667, 1.16666667],
       [0.33333333, 0.66666667, 0.66666667, 1.16666667]])

In [68]:
Api@np.diag(1/np.sum(Api@H4.T@H4,axis=1))@Api@H4.T@H4

array([[0.4       , 0.        , 0.8       , 0.8       ],
       [0.2       , 0.33333333, 0.73333333, 0.73333333],
       [0.2       , 0.33333333, 1.73333333, 0.73333333],
       [0.2       , 0.33333333, 1.23333333, 1.23333333]])

In [69]:
H4.T@A@H4

array([[0, 0, 2, 0],
       [0, 0, 2, 2],
       [2, 2, 0, 2],
       [0, 2, 2, 2]])

In [70]:
H4.T@H4

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 2]])